name: Combinatorial 50
implementation: Combinatorial
dimension: 1540 # the matrices are 10 * 10 => 55 dimensions (symmetric)
mat_dim: 50

data_file: true_samples.pt  # load samples from out_prefix/file if it exists.
n_samples: 10000            # If the file does not exist, generate samples.

interior_point: ~

beta: 0.01
charlie: 0.01
bound: 5

burn_in: 1000
thin: 1
metro_scale: 1.0
metro_burn: 100

domain_file: ../domain.npz