name: Quadratic 3D
implementation: Quadratic
dimension: 3

data_file: true_samples.pt  # load samples from out_prefix/file if it exists.
n_samples: 10000            # If the file does not exist, generate samples.


domain_file: ../../../data/qc_d3_1.npz
