name: Sphere 3D
implementation: Sphere3D
dimension: 3

data_file: true_samples.pt  # load samples from out_prefix/file if it exists.
n_samples: 10000            # If the file does not exist, generate samples.

interior_point: ~

# domain_file: N/A