name: Sphere 3D
implementation: Sphere3D
dimension: 3

data_file: true_samples.pt  # load samples from out_prefix/file if it exists.
n_samples: 10000            # If the file does not exist, generate samples.

interior_point: [ 0.0, 0.0, 1.0 ]

prior_center: [ 0.0, 0.0, 1.0 ]
prior_scale: [ 3.2, 3.2, 1.0 ]

# domain_file: N/A