name: Watermark
implementation: Watermark
dimension: 12288


###### Dataset configurations ######

# afhq-v2 dataset
data_path: ../../../data/afhqv2-64x64.zip
#data_path: ../../../data/afhqv2-64x64/
basis_path: ../../../data/afhqv2_orthobasis_3x64x64.pt
# ffhq dataset
#data_path: ../../../data/ffhq-64x64.zip
#data_path: ../../../data/ffhq-64x64/
#basis_path: ../../../data/ffhq_orthobasis_3x64x64.pt

use_pyspng: true
max_size: ~
#use_labels: falseasd
#xflip: false
dataset_seed: 42
dataset_cache: false
