hydra:
  run:
    dir: ../output/effi/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true

target: [ poly ]
repeat: 1

linear:
  dims: [ 256 ]
  box: 4
  n_cons: 8
  seed: 114
  test_size: 10
  batch_size: [ 10, 100, 1000, 10000, 100000 ]

quadratic:
  dims: [ 256 ]
  box: 4
  n_cons: 8
  seed: 114
  test_size: 10
  batch_size: [ 10, 100, 1000, 10000, 100000 ]

soc:
  dims: [ 256 ]
  box: 4
  n_cons: 8
  seed: 114
  test_size: 10
  batch_size: [ 10, 100, 1000, 10000, 100000 ]

# PSD
lmi:
  dims: [ 256 ]
  mat_dim: 16
  box: 4
  n_cons: 8
  seed: 114
  test_size: 10
  batch_size: [ 10, 100, 1000, 10000, 100000 ]

poly:
  dims: [ 2, 4, 8 ]
  degrees: [ 1, 2, 4 ]
  n_cons: 1
  seed: 114
  test_size: 10
  batch_size: [ 10, 100, 1000 ]
  eig_max: 1.0
  eig_min: 0.0001 # must be positive
  thresh: 1e6
  tol: 1e-4