defaults:
  - _self_
  - example: polytope2d
  - method: vanilla
  - velocity: trivial2
  - train: naive
  - test: common

hydra:
  run:
    dir: output/${example.name}/${now:%m-%d %H:%M}-${method.name}
  job:
    chdir: true

accelerator: cpu
devices: auto

out_prefix: ../ # this is the project_dir/output/${example_name}

# leave it to null for default final checkpoint, i.e., ${out_prefix}/${method.name}-final.ckpt
# by providing a checkpoint name, the final checkpoint will be saved to ${out_prefix}/${final_model}.ckpt
# override test.checkpoint to load a specific checkpoint, i.e., ${out_prefix}/${test.checkpoint}.ckpt
final_model: ~

#action: train # test
action: test
