epoch: 1000
batch_size: 256

loss: MSELoss

optimizer: Adam
optimizer_args:
  lr: 5e-3
  weight_decay: 1e-5

# LRStep
scheduler_args:
  gamma: 0.99
  step_size: 100

checkpoint: 100 # save checkpoints every {} epochs